### ISSUE TITLE
Merge 'Digital Communication' directories

### ISSUE THREAD

**Issue by marwahmanbir** [marwahmanbir/OpenEDU#16]
There are two directories for Digital Communication subject which can be merged into one by moving the file under [second directory](https://github.com/marwahmanbir/OpenEDU/tree/master/Digital%20Communication) to the [first one](https://github.com/marwahmanbir/OpenEDU/tree/master/Digital%20Communication%20).

**Comment by marwahmanbir** [comment]
:wave: Hey @Hemshree! Since you've created the second directory for the subject, would you like to merge the two? :smile:

**Comment by Hemshree** [comment]
Oh, definitely! Created it by mistake. You can merge both of the directories.

**Comment by marwahmanbir** [comment]
Would you like to merge them since that contribution was by you @Hemshree? :slightly_smiling_face:

**Comment by shubhamsah** [comment]
I solved this 🙂.

**Comment by marwahmanbir** [comment]
Thanks @shubhamsah!
Note for reference: Solved in PR #19
