### ISSUE TITLE
Duplicate files 

### ISSUE THREAD

**Issue by chanpreet1999** [marwahmanbir/OpenEDU#20]
The Data Structures folder consists of many dublicate files with different names like `tree.txt.docx` `tree.docx` and many more

**Comment by marwahmanbir** [comment]
:wave: Hi @chanpreet1999! Thanks for pointing this out! 
Would you like to make a PR resolving this issue?

**Comment by chanpreet1999** [comment]
yeah sure!

**Comment by chanpreet1999** [comment]
You can expect a PR from me by tomorrow or the day after 💯

**Comment by chanpreet1999** [comment]
Hey man, I tried thrice to clone the repo but every time it shows 
```
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
```
Maybe the repo is too big to clone to local system

Here's  a screenshot of the same
![image](https://user-images.githubusercontent.com/34856246/85669935-fd2f8900-b6dd-11ea-918e-a3f0b15d7f18.png)

**Comment by marwahmanbir** [comment]
Hey @chanpreet1999, could you please try cloning the repo after running this command:
`$ git config --global core.compression 0`

**Comment by chanpreet1999** [comment]
okay i'll try it out, by the way how did you bypass git's preset limit of 100MB, quite interesting!

**Comment by marwahmanbir** [comment]
I'm not exactly sure what all I did to break that limit but as far as I remember, I switched the repository from HTTPS to SSH through command line.
